import { useEffect, useState } from 'react';
import { Bar, BarChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { GitCompareArrows, LoaderCircle } from 'lucide-react';
import { compareLocations, searchLocation } from '../../services/geeApi';

const defaultDistricts = ['Raipur', 'Bastar', 'Dantewada'];
const value = (item, key) => { const data = item?.[key]; if (!data) return null; return key === 'solar' ? data.potential : key === 'water' ? data.stressIndex : key === 'nightLights' ? data.averageRadiance : key === 'vegetation' ? data.ndvi : key === 'temperature' ? data.landSurfaceTemperature : null; };
export default function DistrictComparison() {
  const [selected, setSelected] = useState(defaultDistricts);
  const [locations, setLocations] = useState([]); const [chart, setChart] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { const controller = new AbortController(); Promise.all(defaultDistricts.map((district) => searchLocation(district, controller.signal))).then((responses) => compareLocations(responses.map((response) => response.results[0]), controller.signal)).then((response) => { const results = response.comparison || []; setLocations(results); setChart(results.map((item) => ({ name: item.location.name, Solar: value(item, 'solar'), Water: value(item, 'water'), NDVI: value(item, 'vegetation') }))); }).catch((err) => { if (err.name !== 'AbortError') setError('Unable to load comparison data.'); }).finally(() => setLoading(false)); return () => controller.abort(); }, []);
  const toggle = (name) => setSelected((current) => current.includes(name) ? current.length > 2 ? current.filter((item) => item !== name) : current : current.length < 5 ? [...current, name] : current);
  return <section className="gee-section gee-compare-section"><div className="gee-container"><div className="gee-heading"><div><div className="gee-section-kicker">MAKE THE CASE FOR INVESTMENT</div><h2>Compare Locations</h2></div><p>Compare up to five locations using backend indicators.</p></div><div className="gee-compare-controls">{defaultDistricts.map((name) => <button type="button" className={selected.includes(name) ? 'active' : ''} onClick={() => toggle(name)} key={name}><GitCompareArrows size={15} /> {name}</button>)}</div>{loading && <div className="gee-analysis-loading"><LoaderCircle className="gee-spin" size={20} /> Loading comparison...</div>}{error && <div className="gee-error" role="alert">{error}</div>}{!loading && !error && <div className="gee-compare-layout"><div className="gee-table-wrap"><table><thead><tr><th>Indicator</th>{locations.map((item) => <th key={item.location.name}>{item.location.name}</th>)}</tr></thead><tbody>{[['Solar', 'solar', 'rating'], ['Water stress', 'water', 'rating'], ['Night lights', 'nightLights', 'priority'], ['NDVI', 'vegetation', 'rating'], ['Temperature', 'temperature', 'rating'], ['Priority', 'overallPriority', null]].map(([label, key, field]) => <tr key={key}><td>{label}</td>{locations.map((item) => <td key={item.location.name}>{field ? item[key]?.[field] || 'Not available' : item[key] || 'Not available'}</td>)}</tr>)}</tbody></table></div><div className="gee-chart-card"><h3>Returned indicator values</h3><ResponsiveContainer width="100%" height={230}><BarChart data={chart}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2eee5" /><XAxis dataKey="name" tick={{ fontSize: 11 }} /><YAxis tick={{ fontSize: 11 }} /><Tooltip /><Legend /><Bar dataKey="Solar" fill="#f59e0b" radius={[5, 5, 0, 0]} /><Bar dataKey="Water" fill="#0ea5e9" radius={[5, 5, 0, 0]} /><Bar dataKey="NDVI" fill="#22c55e" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></div></div>}</div></section>;
}
