import { Droplets, Leaf, Moon, Sun, Thermometer } from 'lucide-react';
const meta = [
	{ key: 'solar', label: 'Solar Potential', getValue: (item) => item.potential, getUnit: (item) => item.unit, icon: Sun, tone: 'yellow', description: 'Satellite-derived solar radiation' },
	{ key: 'water', label: 'Water Stress', getValue: (item) => item.rating, getUnit: (item) => item.rainfallMm == null ? 'Rainfall-based proxy' : `Rainfall: ${item.rainfallMm.toFixed(2)} mm`, icon: Droplets, tone: 'blue', description: 'Rainfall-based proxy' },
	{ key: 'nightLights', label: 'Energy Access Proxy', getValue: (item) => item.averageRadiance, getUnit: (item) => item.unit, icon: Moon, tone: 'purple', description: 'Night-light energy-access proxy' },
	{ key: 'vegetation', label: 'Vegetation', getValue: (item) => item.ndvi == null ? null : `NDVI ${item.ndvi.toFixed(3)}`, getUnit: () => 'NDVI', icon: Leaf, tone: 'green', description: 'Normalized Difference Vegetation Index' },
	{ key: 'temperature', label: 'Land Surface Temperature', getValue: (item) => item.landSurfaceTemperature, getUnit: (item) => item.unit, icon: Thermometer, tone: 'orange', description: 'Daytime land-surface temperature' },
];
const displayValue = (value) => value == null || Number.isNaN(value) ? 'Not available' : value;
export default function KeyIndicators({ analysis }) { return <section className="gee-section gee-container"><div className="gee-heading"><div><div className="gee-section-kicker">EVIDENCE FOR EVERY DECISION</div><h2>Key Indicators</h2></div><span className="gee-data-badge">● Satellite-derived indicators</span></div><div className="gee-indicator-grid">{meta.map(({ key, label, getValue, getUnit, icon: Icon, tone, description }) => { const item = analysis[key] || {}; return <article className={`gee-indicator ${tone}`} key={key}><div className="gee-indicator-icon"><Icon size={20} /></div><span>{label}</span><strong>{displayValue(getValue(item))}</strong><small>{displayValue(getUnit(item))}</small><em>{description}</em></article>; })}</div></section>; }
